// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UbvqY3Uuw7fl11SJLRyxrguyFCa0sgY',
    appId: '1:997144983657:web:ef1b3a722910fafe2e0af8',
    messagingSenderId: '997144983657',
    projectId: 'tourism-app-27c37',
    authDomain: 'tourism-app-27c37.firebaseapp.com',
    storageBucket: 'tourism-app-27c37.appspot.com',
    measurementId: 'G-FNE6NFVRVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPL1cvVkjqYVzj-BgMzBxVAnXMSG6odFM',
    appId: '1:997144983657:android:b4e54d7d549ba5442e0af8',
    messagingSenderId: '997144983657',
    projectId: 'tourism-app-27c37',
    storageBucket: 'tourism-app-27c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYli-5IjcN7ibnmuo7bLDEMKNVszCJoZw',
    appId: '1:997144983657:ios:c8c97d63d7d8deb92e0af8',
    messagingSenderId: '997144983657',
    projectId: 'tourism-app-27c37',
    storageBucket: 'tourism-app-27c37.appspot.com',
    iosClientId: '997144983657-1u9ue3ua5n16uqkbj1m2nvq4sgdaefcd.apps.googleusercontent.com',
    iosBundleId: 'demo.beautifuldestinations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYli-5IjcN7ibnmuo7bLDEMKNVszCJoZw',
    appId: '1:997144983657:ios:c8c97d63d7d8deb92e0af8',
    messagingSenderId: '997144983657',
    projectId: 'tourism-app-27c37',
    storageBucket: 'tourism-app-27c37.appspot.com',
    iosClientId: '997144983657-1u9ue3ua5n16uqkbj1m2nvq4sgdaefcd.apps.googleusercontent.com',
    iosBundleId: 'demo.beautifuldestinations',
  );
}
